### ISSUE TITLE
uwu

### ISSUE THREAD

**Issue by wolfdizz** [Danka32/Adopted-prntscrScrapper#2]

**Comment by Danka32** [comment]
It saves automatically in file that stay in your cmd. 
Example code for Windows cmd: cd C:\Users\Name\Desktop\scrapper
and code will save all pictures in file "scrapper"

**Comment by Danka32** [comment]
Possibly in cmd you wrote wrong way to file, becasue it should to save in file that stay in command.
May be you wrote your way without C:\Users\Name\Destop

**Comment by aye56rus** [comment]
record the best video so that we understand what to do with full instruction

**Comment by Valido1** [comment]
agree with aye56rus
